services:

  mariadb:
    image: mariadb:lts
    container_name: sftshop_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - sftshopdbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: sftshop_adminer
    restart: always
    ports:
      - 8006:8080

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1      

volumes:
  sftshopdbdata:
